#THIS IS A SAMPLE CONFIG FILE. 
#To run the bot you need to make a copy of this file named "confg.yml" and replace the placeholder values


apitoken: api-token-here

log: 'path/to/log/file'

subgroups:
                - id1
                - id2
